### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by probonopd** [blindchimp/dwyco#1]
How to build the Qt5-based application?

Using https://github.com/probonopd/dwyco/blob/patch-1/.travis.yml, running into
```
g++: error: /home/travis/build/probonopd/dwyco/phoo/../bld/cdc32/libcdc32.a: No such file or directory
g++: error: /home/travis/build/probonopd/dwyco/phoo/../bld/vc/libvc.a: No such file or directory
g++: error: /home/travis/build/probonopd/dwyco/phoo/../bld/crypto5/libcrypto5.a: No such file or directory
g++: error: /home/travis/build/probonopd/dwyco/phoo/../bld/dwcls/libdwcls.a: No such file or directory
g++: error: /home/travis/build/probonopd/dwyco/phoo/../bld/gsm/libgsm.a: No such file or directory
g++: error: /home/travis/build/probonopd/dwyco/phoo/../bld/ppm/libppm.a: No such file or directory
g++: error: /home/travis/build/probonopd/dwyco/phoo/../bld/pgm/libpgm.a: No such file or directory
g++: error: /home/travis/build/probonopd/dwyco/phoo/../bld/pbm/libpbm.a: No such file or directory
g++: error: /home/travis/build/probonopd/dwyco/phoo/../bld/jenkins/libjenkins.a: No such file or directory
g++: error: /home/travis/build/probonopd/dwyco/phoo/../bld/v4lcap/libv4lcap.a: No such file or directory
g++: error: /home/travis/build/probonopd/dwyco/phoo/../bld/qt-qml-models/libQtQmlModels.a: No such file or directory
g++: error: /home/travis/build/probonopd/dwyco/phoo/../lib/libuv.a: No such file or directory
make[1]: *** [phoo] Error 1
```

It would be great if clear step-by-step instructions (ideally for Ubuntu trusty) could be given in the README.md.

**Comment by probonopd** [comment]
Apparently https://github.com/blindchimp/dwyco/blob/master/phoobld/build.sh gives some clues... but I still don't succeed.

**Comment by blindchimp** [comment]
I successfully built and run phoo on a virgin Trusty VM this afternoon. I updated the phoobld/README file with step by step instructions. Let me know if this gets things working for you.

**Comment by probonopd** [comment]
Succeeded in building. Looks like you have to  `cp libuv.a ../../lib/libuv.a` because it is not picked up from the default location, `/usr/lib`, and to add `DWYCO_CONFDIR=phoobld` to the `qmake` command.

Now I seem to be missing the desktop file. Is there one?

**Comment by probonopd** [comment]
```
$ qmake CONFIG+=release PREFIX=/usr DWYCO_CONFDIR=phoobld phoobld.pro
$ make -j$(nproc)
$ make INSTALL_ROOT=appdir -j$(nproc) install
```
results in
```
$ find appdir/
appdir/
appdir/opt
appdir/opt/phoo
appdir/opt/phoo/bin
appdir/opt/phoo/bin/phoo
```
Where does the hardcoded `/opt/phoo/bin` come from? Given my configuration, I would have expected to see 

```
appdir/usr/bin/phoo
appdir/usr/share/applications/phoo.desktop
appdir/usr/share/icons/hicolor/256x256/apps/phoo.png
```

Can you make it so?

**Comment by probonopd** [comment]
I case you haven't guessed it, I am working on producing an AppImage.

**Comment by blindchimp** [comment]
I think qmake must create a default "install" target with the /opt path in it, at least on MacOS it does. Let me check the qmake docs and see if there is a way to override the install path (I haven't used the "install" target, since I don't usually install programs to system directories.)

**Comment by blindchimp** [comment]
I modified the README with new instructions and a new build script "phoobld.sh" at the top level that, with any luck, will create an appdir. I just threw together the .desktop and icon file, so they may not be exactly right, but the build did work on trusty.

**Comment by probonopd** [comment]
Doesn't seem to make much of a difference for me - or am I doing it wrong?

https://travis-ci.org/probonopd/dwyco/jobs/378417031#L3279-L3296

**Comment by blindchimp** [comment]
looks like whatever you are cloning in your travis script hasn't been updated to the latest from my repo... i had to add some funky install stuff to phoo.pro to override qmake's default install location.

**Comment by probonopd** [comment]
You are so right. Stupid me. Thanks!

**Comment by probonopd** [comment]
Thank you, I can build now. However, the built executable fails with 

```
firejail ./BeingTested.AppImage ("Default", "Material", "Universal")
qrc:/MsgView.qml:26: TypeError: Cannot call method 'stop_zap_view' of null
qrc:/SimpleChatBox.qml:699: TypeError: Cannot call method 'get_ignore' of null
qrc:/DwycoVidRec.qml:28: TypeError: Cannot call method 'stop_zap_record' of null
PulseAudioService: pa_context_connect() failed
PulseAudioService: pa_context_connect() failed
PulseAudioService: pa_context_connect() failed
qrc:/MsgView.qml:101:5: QML Page: Binding loop detected for property "contentHeight"
qrc:/main.qml:322:5: QML Page: Binding loop detected for property "contentHeight"
qrc:/main.qml:432:5: QML Rectangle: StackView has detected conflicting anchors. Transitions may not execute properly.
PulseAudioService: pa_context_connect() failed
```

Do you know what this means/how it can be fixed? Thanks.

(Note: PulseAudio may be missing on the system on which the automated test is run.)

**Comment by blindchimp** [comment]
I downloaded the appimage from your repo and it worked fine on my Trusty VM. Nice work, that's a huge improvement in usability.

Those qml errors are "normal", they look exactly like what I get when I'm debugging.

If it crashed because it couldn't access an audio device, that is probably just a program bug I need to fix. If it looks like it is a deployment problem (like a plugin issue), I'll update this issue.

Does your automated test environment provide any multimedia devices? Or is it basically
a headless server?

**Comment by probonopd** [comment]
It is basically a headless server with a virtual Xorg device. You can see it here:
https://github.com/AppImage/appimage.github.io/blob/master/.travis.yml

**Comment by blindchimp** [comment]
ok, so I fixed the crash. I set up a trusty server similar to your test server and was able to run phoo on the virtual FB and grab a screen PNG. I modified the default startup size to fit the virtual FB size. It is working as it should, sitting waiting for user input to continue (see below). 

Am I right in assuming that running it isn't really for "testing", but rather just to get it up and grab a screen that can be displayed in your appimage hub directory?

---------
![image](https://user-images.githubusercontent.com/122083/40081406-1ac05376-584b-11e8-8aba-4c4505246dc9.png)

**Comment by probonopd** [comment]
👍 thanks for fixing this. https://github.com/AppImage/appimage.github.io inspects the AppImage, runs the automated tests (as part of which a screenshot is taken) and puts the application into the catalog after it has passed the tests. The screenshot taken will be displayed in AppImageHub, unless the AppImage comes with an [AppStream](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) metadata file that points to another screenshot.

**Comment by probonopd** [comment]
Hi @blindchimp have you seen my pull request? Thanks for considering.

**Comment by blindchimp** [comment]
yep, got it all wired up this morning and it appears to be creating and uploading the appimage to releases just fine. thanks!
